# Generated by Django 4.1.2 on 2022-10-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_addother'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCar',
            new_name='Bike',
        ),
        migrations.RenameModel(
            old_name='AddBike',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='AddOther',
            new_name='Other',
        ),
    ]
