# Generated by Django 4.1.2 on 2022-10-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_bikeadd_caradd_otheradd_delete_bike_delete_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=20000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('Brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('KM', models.IntegerField()),
                ('Fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], default='Petrol', max_length=40)),
                ('Ownership', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=120)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=20000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('Brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('KM', models.IntegerField()),
                ('Fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], default='Petrol', max_length=40)),
                ('Ownership', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=120)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=20000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('Vehicle_Type', models.CharField(choices=[('Bicycle', 'Bicycle'), ('JCB', 'JCB'), ('AutoRicksha', 'AutoRicksha'), ('BUS', 'BUS'), ('Lory', 'Lory'), ('Pickup', 'Pickup')], default='bicycle', max_length=2000)),
                ('Brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('KM', models.IntegerField()),
                ('Fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], default='Petrol', max_length=40)),
                ('Ownership', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=120)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='BikeAdd',
        ),
        migrations.DeleteModel(
            name='CarAdd',
        ),
        migrations.DeleteModel(
            name='OtherAdd',
        ),
    ]
