# Generated by Django 4.1.2 on 2022-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_bike_car_other_delete_bikeadd_delete_caradd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
