# Generated by Django 4.1.2 on 2022-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_other_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
