# Generated by Django 4.1.2 on 2022-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_bike_id_alter_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Issue', models.CharField(choices=[('My item was sold(mention item id in detail section)', 'My item was sold(mention item id in decription)'), ('Report an abuse', 'Report an abuse'), ('Report fraud activity', 'Report fraud activity'), ('Secutrity Vulnerability', 'Secutrity Vulnerability'), ('other', 'other')], default='My item was sold(mention item id in decription)', max_length=500)),
                ('Details', models.TextField()),
            ],
        ),
    ]
